import Head from "next/head";
import Image from "next/image";
import { Product, FooterBanner, HeroBanner, Footer } from "../components";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroBanner />
      <div className="products-heading">
        <h2>Beset Selling Products</h2>
        <p>speackers of many variations</p>
      </div>
      <div className="products-container">
        {["product 1", "product 2"].map((product) => product)}
      </div>
      <Footer />
    </>
  );
}
