import Head from "next/head";
import Image from "next/image";
import { Product, FooterBanner, HeroBanner, Footer } from "../components";
import { client } from "../lib/client";
export default function Home({ products, bannerData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroBanner />
      {console.log(bannerData)}
      <div className="products-heading">
        <h2>Beset Selling Products</h2>
        <p>speackers of many variations</p>
      </div>
      <div className="products-container">
        {products?.map((product) => product.name)}
      </div>
      <Footer />
    </>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData },
  };
};
